### ISSUE TITLE
Abstract Prisma parts away to improve flexibility

### ISSUE THREAD

**Issue by SpaceK33z** [Volst/graphql-authentication#26]
@maticzav came with the great idea of making this package not specific to Prisma anymore. I have to say I was hesistant at first but I'm convinced this is the best way to go now.

Prisma would still be supported and be the default "adapter", so it will not require many (or at all) code changes from existing users.

Direct benefits;

- It will be possible to write adapters for it, e.g. for Auth0 (specifically Auth0 might require some more customizations, don't know yet).
- It's easier to write tests for it (also this refactoring is the perfect moment to *finally* write tests).
- Even if you use Prisma, you will have way more flexibility over your own data model. E.g. if you want to update a special field on your `User` model whenever the user logs in.

I think this would also be a good moment to rename the package to something `graphql-something-auth` (replace something for... I don't know yet).

- [x] Rename package
- [x] Finish Prisma adapter
- [x] Provide typings for adapter
- [x] Make it clear Prisma is just an adapter in the docs
- [x] Split package in a core package and Prisma package
- [x] Mention in docs that you can modify the Prisma adapter
- [x] Add docs about custom adapters
- [x] Remove hardcoded `db` property
- [x] Test package on my own Foed project
- [x] Rename GitHub repository

**Comment by SpaceK33z** [comment]
Finally this is done!

**Comment by haysclark** [comment]
Ideally, it would be great if _graphql-authentication_ could use _graphql-imports_ to extend Prisma's  _datamodel.graphql_ to add the _User_ object.  It looks like this feature is not supported yet: https://github.com/prisma/prisma/issues/1913
