### ISSUE TITLE
Add example to Prisma repo

### ISSUE THREAD

**Issue by SpaceK33z** [Volst/graphql-authentication#35]
Note for myself that I need to make a full example and submit it as a PR to the Prisma repository.

**Comment by SpaceK33z** [comment]
@erichodges nice :). I made a PR, https://github.com/prismagraphql/prisma/pull/2778, do you have time to verify if everything works?

**Comment by SpaceK33z** [comment]
That sounds good! Adding a React/Prisma boilerplate surely would be a good idea. I already have an open source project that uses it, https://github.com/Volst/foed, which is built with React+Prisma+GraphQL Authentication.

My Prisma PR was merged so closing this :).

**Comment by erichodges** [comment]
Ah ok, cool. I will look at your project...sounds like that could be turned into a boilerplate. Thanks for your work in this area!
